prefix = ..
include $(prefix)/config.mk
include $(makedir)/common.mk
include $(makedir)/fileinfo.mk
include $(makedir)/histogram.mk
SHOWDATA += splitdir

## source data files in this directory (wildcards allowed)
DATA_HERE =
## source data files in datadirs (wildcards allowed)
DATA_LINK = *.cossin.pca
DROPSUFFIX = .cossin.pca

## settings
# see config.mk

## default targets
all += calc

## call macros
$(call_macros)
