prefix = ..
include $(prefix)/config.mk
include $(makedir)/common.mk
include $(makedir)/clustering.mk

## source data files in this directory (wildcards allowed)
DATA_HERE =
## source data files in datadirs (wildcards allowed)
DROPSUFFIX = $(PROJDROPSUFFIX)
DATA_LINK = $(addsuffix ${PROJSUFFIX},${RAWDATA})

## settings
# see config.mk

## default targets
all +=

## call macros
$(call_macros)
