prefix = ../../../..
datadirs = ..
include $(prefix)/config.mk
include $(makedir)/common.mk
include $(makedir)/no_neighbors.mk
include $(makedir)/fields.mk

## source data files in this directory (wildcards allowed)
DATA_HERE =
## source data files in datadirs (wildcards allowed)
DATA_LINK = *.dat
DROPSUFFIX = .dat

## settings
ALL +=

## default targets
all += no_neighbor_dependence

## call macros
$(call_macros)
