prefix = ..
makedir = $(prefix)/makefiles
include $(makedir)/common.mk
include $(makedir)/template.mk

## source data files in this directory (wildcards allowed)
DATA_HERE =

## settings

## default targets
all += target
